export const RefFaucets = [
  {
    name: "BanFaucet",
    link: "https://banfaucet.com/?r=14",
    type: "Refferal",
    tags: ["Banano", "Doge"],
  },
  {
    name: "Faucet Crypto",
    link: "https://faucetcrypto.com/ref/1770141",
    type: "Refferal",
    tags: ["ads", "Solana", "Doge", "BTC"],
  },
  {
    name: "Vie Faucet (FP)",
    link: "https://viefaucet.com?r=6224cc8194ae11262f793c32",
    type: "Refferal",
    tags: ["ads", "Solana", "Shiba", "BTC"],
  },
  {
    name: "FaucetPay",
    link: "https://faucetpay.io/?r=3295889",
    type: "Refferal",
    tags: ["ads", "Solana", "BTC", "ETH"],
  },
  {
    name: "FreeSolana (FP)",
    link: "https://freesolana.top/?r=47342",
    type: "Refferal",
    tags: ["ads", "Solana"]
  },
  {
    name: "Play Nano",
    link: "https://playnano.online/?ref=banbucket",
    type: "Refferal",
    tags: ["Nano", "Games", "Surveys"]
  },
  {
    name: "Bonobo.cc",
    link: "https://bonobo.cc/faucet",
    type: "Refferal",
    tags: ["Nano", "Banano", "Exchange"]
  },
]

export const OtherFaucetCryptoTypes = ["Banano", "Nano", "Algorand", "Solana"]

export const OtherFaucets = [
  {
    name: "BanBucket",
    link: "https://www.banbucket.ninja/",
    type: "Banano",
    ads: false,
    rt: "15 Hours",
    health: 100,
    captcha: true,
    limit: -1,
  },
  {
    name: "NanSwap",
    link: "https://nanswap.com/get-free-banano?ref=ban_1j3rqseffoin7x5z5y1ehaqe1n7todza41kdf4oyga8phps3ea31u39ruchu",
    type: "Banano",
    ads: false,
    rt: "1 Week",
    health: 100,
    captcha: false,
    limit: -1,
  },
  {
    name: "Nanswap (N)",
    link: "https://nanswap.com/get-free-nano?ref=nano_3uyr8g44extoefgszk4khpi73qmakqcq9f65babjs9t9uzupbcfcp9jys1me",
    type: "Nano",
    ads: false,
    rt: "1 Week",
    health: 100,
    captcha: false,
    limit: -1,
  },
  {
    name: "Only Bans",
    link: "https://www.only-bans.cc/",
    type: "Banano",
    ads: false,
    rt: "1 Day",
    health: 80,
    captcha: true,
    limit: -1,
  },
  {
    name: "Prussia",
    link: "https://faucet.prussia.dev/",
    type: "Banano",
    ads: false,
    rt: "1 Day",
    health: 80,
    captcha: true,
    limit: -1,
  },
  {
    name: "Get Banano",
    link: "https://getbanano.cc/",
    type: "Banano",
    ads: false,
    rt: "00:00 UTC",
    health: 70,
    captcha: true,
    limit: -1,
  },
  {
    name: "Monkey Talks",
    link: "https://monkeytalks.cc/",
    type: "Banano",
    ads: false,
    rt: "1 Day",
    health: 80,
    captcha: true,
    limit: -1,
  },
  {
    name: "Toga Tech",
    link: "https://solfaucet.togatech.org/",
    type: "Solana",
    ads: true,
    rt: "1 Day",
    health: 100,
    captcha: true,
    limit: -1,
  },
  {
    name: "Algo Drops",
    link: "https://algodrops.org/faucet",
    type: "Algorand",
    ads: false,
    rt: "2 Days",
    health: 100,
    captcha: true,
    limit: 500,
  },
  {
    name: "Algo For Me",
    link: "https://algofor.me/faucet",
    type: "Algorand",
    ads: false,
    rt: "00:00 UTC",
    health: 100,
    captcha: true,
    limit: -1,
  },
  {
    name: "The Algo",
    link: "https://thealgofaucet.com/",
    type: "Algorand",
    ads: false,
    rt: "1 Week",
    health: 100,
    captcha: true,
    limit: -1,
  },
  {
    name: "TryBanano",
    link: "https://www.trybanano.com/",
    type: "Banano",
    ads: false,
    rt: "2 Hours",
    health: 100,
    captcha: true,
    limit: -1,
  },
  {
    name: "Free Nyano",
    link: "https://freenyanofaucet.com/nfaucet",
    type: "Nano",
    ads: false,
    rt: "1 Day",
    health: 100,
    captcha: false,
    limit: -1,
  },
  {
    name: "Try Nano",
    link: "https://www.trynano.io/",
    type: "Nano",
    ads: false,
    rt: "10 Minutes",
    health: 100,
    captcha: false,
    limit: -1,
  },
  {
    name: "K3I",
    link: "https://nanofaucet.online/",
    type: "Nano",
    ads: true,
    rt: "30 Minutes",
    health: 100,
    captcha: false,
    limit: -1,
  },
  {
    name: "K3I",
    link: "https://bananofaucet.online/",
    type: "Banano",
    ads: true,
    rt: "30 Minutes",
    health: 100,
    captcha: false,
    limit: -1,
  },
  {
    name: "Bonobo",
    link: "https://bonobo.cc/faucet",
    type: "Banano",
    ads: false,
    rt: "1 Week",
    health: 100,
    captcha: false,
    limit: -1,
  },
  {
    name: "Baucarp",
    link: "https://baucarp.herokuapp.com/",
    type: "Banano",
    ads: false,
    rt: "1 Day",
    health: 100,
    captcha: false,
    limit: -1,
  },
  {
    name: "Bonobo(N)",
    link: "https://bonobo.cc/faucet",
    type: "Nano",
    ads: false,
    rt: "1 Week",
    health: 100,
    captcha: false,
    limit: -1,
  },
  {
    name: "MiranDaniel",
    link: "https://bananofaucet.cc/",
    type: "Banano",
    ads: false,
    rt: "1 Week",
    health: 100,
    captcha: true,
    limit: -1,
  },
  {
    name: "BananoTime(N)",
    link: "https://faucet.bananotime.com/nano",
    type: "Nano",
    ads: false,
    rt: "1 Day",
    health: 100,
    captcha: true,
    limit: -1,
  },
  {
    name: "BananoTime",
    link: "https://faucet.bananotime.com",
    type: "Banano",
    ads: false,
    rt: "1 Day",
    health: 100,
    captcha: true,
    limit: -1,
  },
  {
    name: "Banano Club",
    link: "https://www.bananofaucet.club/",
    type: "Banano",
    ads: false,
    rt: "1 Day",
    health: 100,
    captcha: true,
    limit: -1,
  },
  {
    name: "Gorilla Nation",
    link: "https://gorillanation.ga/",
    type: "Banano",
    ads: false,
    rt: "1 Day",
    health: 100,
    captcha: true,
    limit: -1,
  },
  {
    name: "Prussia (M)",
    link: "https://www.moonfaucet.cc/",
    type: "Moon",
    ads: false,
    rt: "1 Day",
    health: 100,
    captcha: true,
    limit: -1,
  },
  {
    name: "BananoPlanet",
    link: "https://bananoplanet.cc/faucet",
    type: "Banano",
    ads: true,
    rt: "2 Hours",
    health: 100,
    captcha: true,
    limit: -1,
  },
  {
    name: "NanoRobot",
    link: "https://t.me/NanoFaucetRobot",
    type: "Nano",
    ads: false,
    rt: "18 Hours",
    health: 100,
    captcha: false,
    limit: 330,
  },
  {
    name: "Barrel O'Banana",
    link: "https://www.devinmontes.com/",
    type: "Banano",
    ads: false,
    rt: "1 Day",
    health: 100,
    captcha: false,
    limit: -1,
  },
  {
    name: "Faucet Queen",
    link: "https://faucetqueen.repl.co/",
    type: "Nano",
    ads: false,
    rt: "1 Day",
    health: 100,
    captcha: true,
    limit: -1,
  },
  {
    name: "Changing.cc",
    link: "https://fdg.exchanging.cc/en/338983/",
    type: "Dogecoin",
    ads: true,
    rt: "1 Hour",
    health: 100,
    captcha: false,
    limit: -1,
  },
  {
    name: "Global Hive",
    link: "https://globalhive.io/r/212392",
    type: "ZCash",
    ads: false,
    rt: "1 Day",
    health: 100,
    captcha: false,
    limit: -1,
  },
  {
    name: "Nano2Go",
    link: "https://nano2go.herokuapp.com/",
    type: "Nano",
    ads: false,
    rt: "30 Minutes",
    health: 100,
    captcha: false,
    limit: -1,
  },
  {
    name: "Banano2Go",
    link: "https://nano2go.herokuapp.com/",
    type: "Banano",
    ads: false,
    rt: "30 Minutes",
    health: 100,
    captcha: false,
    limit: -1,
  }
]