export const RefFaucets = [
  {
    name: "BanFaucet",
    link: "https://banfaucet.com/?r=14",
    type: "Refferal",
    tags: ["Banano", "Doge"],
  },
  {
    name: "Faucet Crypto",
    link: "https://faucetcrypto.com/ref/1770141",
    type: "Refferal",
    tags: ["ads", "Solana", "Doge", "BTC"],
  },
  {
    name: "Vie Faucet (FP)",
    link: "https://viefaucet.com?r=6224cc8194ae11262f793c32",
    type: "Refferal",
    tags: ["ads", "Solana", "Shiba", "BTC"],
  },
  {
    name: "FaucetPay",
    link: "https://faucetpay.io/?r=3295889",
    type: "Refferal",
    tags: ["ads", "Solana", "BTC", "ETH"],
  },
  {
    name: "FreeSolana (FP)",
    link: "https://freesolana.top/?r=47342",
    type: "Refferal",
    tags: ["ads", "Solana"]
  }
]

export const OtherFaucetCryptoTypes = ["Banano", "Nano", "Algorand", "Solana"]

export const OtherFaucets = [
  {
    name: "BanBucket",
    link: "https://www.banbucket.ninja/",
    type: "Banano",
    ads: false,
    rt: "15 Hours",
    health: 100,
    captcha: true,
  },
  {
    name: "Only Bans",
    link: "https://www.only-bans.cc/",
    type: "Banano",
    ads: false,
    rt: "1 Day",
    health: 80,
    captcha: true,
  },
  {
    name: "Prussia",
    link: "https://faucet.prussia.dev/",
    type: "Banano",
    ads: false,
    rt: "1 Day",
    health: 80,
    captcha: true,
  },
  {
    name: "Get Banano",
    link: "https://getbanano.cc/",
    type: "Banano",
    ads: false,
    rt: "00:00 UTC",
    health: 70,
    captcha: true,
  },
  {
    name: "Monkey Talks",
    link: "https://monkeytalks.cc/",
    type: "Banano",
    ads: false,
    rt: "1 Day",
    health: 80,
    captcha: true,
  },
  {
    name: "Toga Tech",
    link: "https://solfaucet.togatech.org/",
    type: "Solana",
    ads: true,
    rt: "1 Day",
    health: 100,
    captcha: true,
  },
  {
    name: "Algo Drops",
    link: "https://algodrops.org/faucet",
    type: "Algorand",
    ads: false,
    rt: "2 Days",
    health: 100,
    captcha: true,
  },
  {
    name: "Algo For Me",
    link: "https://algofor.me/faucet",
    type: "Algorand",
    ads: false,
    rt: "00:00 UTC",
    health: 100,
    captcha: true,
  },
  {
    name: "The Algo",
    link: "https://thealgofaucet.com/",
    type: "Algorand",
    ads: false,
    rt: "1 Week",
    health: 100,
    captcha: true,
  },
  {
    name: "Banano Drip",
    link: "https://bananodrip.com/",
    type: "Banano",
    ads: false,
    rt: "00:00 UTC",
    health: 100,
    captcha: true,
  },
  {
    name: "Free Nyano",
    link: "https://freenyanofaucet.com/nfaucet",
    type: "Nano",
    ads: false,
    rt: "1 Day",
    health: 100,
    captcha: false,
  },
  {
    name: "Try Nano",
    link: "https://www.trynano.io/",
    type: "Nano",
    ads: false,
    rt: "10 Minutes",
    health: 100,
    captcha: false,
  },
  {
    name: "K3I",
    link: "https://nanofaucet.online/",
    type: "Nano",
    ads: true,
    rt: "30 Minutes",
    health: 100,
    captcha: false,
  },
  {
    name: "K3I",
    link: "https://bananofaucet.online/",
    type: "Banano",
    ads: true,
    rt: "30 Minutes",
    health: 100,
    captcha: false,
  },
  {
    name: "Bonobo",
    link: "https://bonobo.cc/faucet",
    type: "Banano",
    ads: false,
    rt: "1 Week",
    health: 100,
    captcha: false,
  },
  {
    name: "Baucarp",
    link: "https://baucarp.herokuapp.com/",
    type: "Banano",
    ads: false,
    rt: "1 Day",
    health: 100,
    captcha: false,
  },
  {
    name: "Bonobo(N)",
    link: "https://bonobo.cc/faucet",
    type: "Nano",
    ads: false,
    rt: "1 Week",
    health: 100,
    captcha: false,
  },
  {
    name: "MiranDaniel",
    link: "https://bananofaucet.cc/",
    type: "Banano",
    ads: false,
    rt: "1 Week",
    health: 100,
    captcha: true,
  },
  {
    name: "BananoTime(N)",
    link: "https://faucet.bananotime.com/nano",
    type: "Nano",
    ads: false,
    rt: "1 Day",
    health: 100,
    captcha: true,
  },
  {
    name: "BananoTime",
    link: "https://faucet.bananotime.com",
    type: "Banano",
    ads: false,
    rt: "1 Day",
    health: 100,
    captcha: true,
  },
  {
    name: "Ban Club",
    link: "https://www.bananofaucet.club/",
    type: "Banano",
    ads: false,
    rt: "1 Day",
    health: 100,
    captcha: true,
  },
  {
    name: "Gorilla Nation",
    link: "https://gorillanation.ga/",
    type: "Banano",
    ads: false,
    rt: "1 Day",
    health: 100,
    captcha: true,
  },
  {
    name: "Prussia (M)",
    link: "https://www.moonfaucet.cc/",
    type: "Moon",
    ads: false,
    rt: "1 Day",
    health: 100,
    captcha: true,
  }
  // {
  //   name: "Faucet Queen",
  //   link: "https://faucetqueen.repl.co/",
  //   type: "Nano",
  //   ads: true,
  //   rt: "1 Day",
  //   health: 100,
  //   captcha: true,
  // },
]